// <auto-generated />
namespace BookLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addAddRequiredToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addAddRequiredToBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202003120645501_addAddRequiredToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
